//package com.example.qlbhbe.service.baocao;
//
//import com.example.qlbhbe.dto.SanPhamDTO;
//import com.itextpdf.text.*;
//import com.itextpdf.text.pdf.BaseFont;
//import com.itextpdf.text.pdf.PdfPCell;
//import com.itextpdf.text.pdf.PdfPTable;
//import com.itextpdf.text.pdf.PdfWriter;
//import org.apache.poi.ss.usermodel.Cell;
//import org.apache.poi.ss.usermodel.Row;
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.util.ResourceUtils;
//
//import java.io.FileOutputStream;
//import java.io.IOException;
//import java.time.LocalDate;
//
//public class Test {
//    private static String FILE = "D:/FirstPdf.pdf";
//    private static Font catFont;
//
//
//    static {
//        try {
//            catFont = new Font(BaseFont.createFont("C:\\CDTT\\BE\\arial.ttf"
//                    , BaseFont.IDENTITY_H, BaseFont.EMBEDDED), 18,
//                    Font.BOLD);
//        } catch (DocumentException e) {
//            e.printStackTrace();
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//    }
//
//    private static Font redFont;
//
//    static {
//        try {
//            redFont = new Font(BaseFont.createFont("C:\\CDTT\\BE\\arial.ttf"
//                    , BaseFont.IDENTITY_H, BaseFont.EMBEDDED), 12,
//                    Font.NORMAL, BaseColor.RED);
//        } catch (DocumentException e) {
//            e.printStackTrace();
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//    }
//
//    private static Font subFont;
//
//    static {
//        try {
//            subFont = new Font(BaseFont.createFont("C:\\CDTT\\BE\\arial.ttf"
//                    , BaseFont.IDENTITY_H, BaseFont.EMBEDDED), 16,
//                    Font.BOLD);
//        } catch (DocumentException e) {
//            e.printStackTrace();
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//    }
//
//    private static Font smallBold;
//
//    static {
//        try {
//            smallBold = new Font(BaseFont.createFont("C:\\CDTT\\BE\\arial.ttf"
//                    , BaseFont.IDENTITY_H, BaseFont.EMBEDDED), 12,
//                    Font.BOLD);
//        } catch (DocumentException e) {
//            e.printStackTrace();
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//    }
//
//    public static void main(String[] args) {
//        try {
//            Document document = new Document();
//            PdfWriter.getInstance(document, new FileOutputStream(FILE));
//            document.open();
//            addMetaData(document);
//            addTitlePage(document);
//            addContent(document);
//            document.close();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
//
//    // iText allows to add metadata to the PDF which can be viewed in your Adobe
//    // Reader
//    // under File -> Properties
//    private static void addMetaData(Document document) {
//        document.addTitle("My first PDF");
//        document.addSubject("Using iText");
//        document.addKeywords("Java, PDF, iText");
//        document.addAuthor("Lars Vogel");
//        document.addCreator("Lars Vogel");
//
//    }
//
//    private static void addTitlePage(Document document)
//            throws DocumentException, IOException {
//        Paragraph preface = new Paragraph();
//        // We add one empty line
//        addEmptyLine(preface, 1);
//        // Lets write a big header
//        setRow(preface, "Báo cáo tồn kho", catFont, Element.ALIGN_CENTER);
//
//        addEmptyLine(preface, 1);
//        // Will create: Report generated by: _name, _date
//        setRow(preface, "Hà Nội, ngày " + LocalDate.now().getDayOfMonth() + ", tháng " + LocalDate.now().getMonthValue() + ", năm " + LocalDate.now().getYear(), smallBold, Element.ALIGN_RIGHT);
//
//        addEmptyLine(preface, 1);
//
//        document.add(preface);
//    }
//
//    private static void setRow(Paragraph preface, String content, Font font, int style) {
//        Paragraph tmp = new Paragraph(content, font);
//        tmp.setAlignment(style);
//        preface.add(tmp);
//    }
//
//    private static void addContent(Document document) throws DocumentException {
//        Paragraph paragraph = new Paragraph();
//        // add a table
//        createTable(paragraph);
//
//        // now add all this to the document
//        document.add(paragraph);
//
//
//    }
//
//    private static void createTable(Paragraph paragraph)
//            throws BadElementException {
//        PdfPTable table = new PdfPTable(3);
//        PdfPCell c1 = null;
//
//        setHeaderTable(table, "Mã sản phẩm", Element.ALIGN_CENTER, c1);
//        setHeaderTable(table, "Tên Sản Phẩm", Element.ALIGN_CENTER, c1);
//        setHeaderTable(table, "Danh Mục", Element.ALIGN_CENTER, c1);
//        setHeaderTable(table, "Giá Bán Niêm Yết", Element.ALIGN_CENTER, c1);
//        setHeaderTable(table, "Đơn vị", Element.ALIGN_CENTER, c1);
//        setHeaderTable(table, "Số Lượng Xuất", Element.ALIGN_CENTER, c1);
//        setHeaderTable(table, "Số Lượng Tồn", Element.ALIGN_CENTER, c1);
//        setHeaderTable(table, "Cửa Hàng", Element.ALIGN_CENTER, c1);
//        table.setHeaderRows(1);
//
//        for (SanPhamDTO sanPhamDTO1 : sanPhamDTOList) {
//            Row row = sheet.createRow(rowNum++);
//
//            Cell cell = row.createCell(0);
//            cell.setCellValue(sanPhamDTO1.getMaSanPham());
//            cell.setCellStyle(cellStyle);
//
//            Cell cell1 = row.createCell(1);
//            cell1.setCellValue(sanPhamDTO1.getTenSanPham());
//            cell1.setCellStyle(cellStyle);
//
//            Cell cell2 = row.createCell(2);
//            cell2.setCellValue(sanPhamDTO1.getTenDanhMuc());
//            cell2.setCellStyle(cellStyle);
//
//            Cell cell3 = row.createCell(3);
//            cell3.setCellValue(sanPhamDTO1.getGiaBanNiemYet());
//            cell3.setCellStyle(cellStyle);
//
//            Cell cell4 = row.createCell(4);
//            cell4.setCellValue(sanPhamDTO1.getGiaNhapNiemYet());
//            cell4.setCellStyle(cellStyle);
//
//            Cell cell41 = row.createCell(5);
//            cell41.setCellValue(sanPhamDTO1.getDonVi());
//            cell41.setCellStyle(cellStyle);
//
//            Cell cell5 = row.createCell(6);
//            cell5.setCellValue(sanPhamDTO1.getSoLuongNhap());
//            cell5.setCellStyle(cellStyle);
//
//            Cell cell6 = row.createCell(7);
//            cell6.setCellValue(sanPhamDTO1.getSoLuongBan());
//            cell6.setCellStyle(cellStyle);
//
//            Cell cell7 = row.createCell(8);
//            cell7.setCellValue(sanPhamDTO1.getSoLuongTon());
//            cell7.setCellStyle(cellStyle);
//
//            Cell cell8 = row.createCell(9);
//            cell8.setCellValue(sanPhamDTO1.getTenCuaHang());
//            cell8.setCellStyle(cellStyle);
//        }
//
//
//
//        table.addCell("1.0");
//        table.addCell("1.1");
//        table.addCell("1.2");
//        table.addCell("2.1");
//        table.addCell("2.2");
//        table.addCell("2.3");
//
//        paragraph.add(table);
//    }
//
//    private static void setHeaderTable(PdfPTable table, String name, int style, PdfPCell c1) {
//        c1 = new PdfPCell(new Phrase(name));
//        c1.setHorizontalAlignment(style);
//        table.addCell(c1);
//    }
//
//    private static void addEmptyLine(Paragraph paragraph, int number) {
//        for (int i = 0; i < number; i++) {
//            paragraph.add(new Paragraph(" "));
//        }
//    }
//}